"""empty message

Revision ID: 331320b4f8d1
Revises: b59418d33935
Create Date: 2026-02-20 12:41:58.092954

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision: str = "331320b4f8d1"
down_revision: Union[str, Sequence[str], None] = "b59418d33935"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _table_exists(inspector: Inspector, table_name: str) -> bool:
    return table_name in inspector.get_table_names()


def _index_exists(inspector: Inspector, table_name: str, index_name: str) -> bool:
    if not _table_exists(inspector, table_name):
        return False
    return any(
        index.get("name") == index_name for index in inspector.get_indexes(table_name)
    )


def _column_exists(inspector: Inspector, table_name: str, column_name: str) -> bool:
    if not _table_exists(inspector, table_name):
        return False
    return any(
        column.get("name") == column_name
        for column in inspector.get_columns(table_name)
    )


def _foreign_key_exists(
    inspector: Inspector, table_name: str, constraint_name: str
) -> bool:
    if not _table_exists(inspector, table_name):
        return False
    return any(
        foreign_key.get("name") == constraint_name
        for foreign_key in inspector.get_foreign_keys(table_name)
    )


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    inspector = sa.inspect(op.get_bind())

    agent_runs_workspace_ref_id_idx = op.f("ix_agent_runs_workspace_ref_id")
    if _index_exists(inspector, "agent_runs", agent_runs_workspace_ref_id_idx):
        op.drop_index(
            agent_runs_workspace_ref_id_idx,
            table_name="agent_runs",
            if_exists=True,
        )

    agent_runs_workspace_scope_idx = op.f("ix_agent_runs_workspace_scope")
    if _index_exists(inspector, "agent_runs", agent_runs_workspace_scope_idx):
        op.drop_index(
            agent_runs_workspace_scope_idx,
            table_name="agent_runs",
            if_exists=True,
        )

    if _column_exists(inspector, "agent_runs", "workspace_scope"):
        op.drop_column("agent_runs", "workspace_scope")

    if _column_exists(inspector, "agent_runs", "workspace_ref_id"):
        op.drop_column("agent_runs", "workspace_ref_id")

    scheduled_tasks_project_id_idx = op.f("ix_agent_scheduled_tasks_project_id")
    if _index_exists(
        inspector, "agent_scheduled_tasks", scheduled_tasks_project_id_idx
    ):
        op.drop_index(
            scheduled_tasks_project_id_idx,
            table_name="agent_scheduled_tasks",
            if_exists=True,
        )

    scheduled_tasks_workspace_scope_idx = op.f(
        "ix_agent_scheduled_tasks_workspace_scope"
    )
    if _index_exists(
        inspector, "agent_scheduled_tasks", scheduled_tasks_workspace_scope_idx
    ):
        op.drop_index(
            scheduled_tasks_workspace_scope_idx,
            table_name="agent_scheduled_tasks",
            if_exists=True,
        )

    scheduled_tasks_project_fk = op.f("agent_scheduled_tasks_project_id_fkey")
    if _foreign_key_exists(
        inspector, "agent_scheduled_tasks", scheduled_tasks_project_fk
    ):
        op.drop_constraint(
            scheduled_tasks_project_fk,
            "agent_scheduled_tasks",
            type_="foreignkey",
        )

    if _column_exists(inspector, "agent_scheduled_tasks", "project_id"):
        op.drop_column("agent_scheduled_tasks", "project_id")

    if _column_exists(inspector, "agent_scheduled_tasks", "workspace_scope"):
        op.drop_column("agent_scheduled_tasks", "workspace_scope")

    agent_sessions_workspace_ref_id_idx = op.f("ix_agent_sessions_workspace_ref_id")
    if _index_exists(inspector, "agent_sessions", agent_sessions_workspace_ref_id_idx):
        op.drop_index(
            agent_sessions_workspace_ref_id_idx,
            table_name="agent_sessions",
            if_exists=True,
        )

    agent_sessions_workspace_scope_idx = op.f("ix_agent_sessions_workspace_scope")
    if _index_exists(inspector, "agent_sessions", agent_sessions_workspace_scope_idx):
        op.drop_index(
            agent_sessions_workspace_scope_idx,
            table_name="agent_sessions",
            if_exists=True,
        )

    if _column_exists(inspector, "agent_sessions", "workspace_scope"):
        op.drop_column("agent_sessions", "workspace_scope")

    if _column_exists(inspector, "agent_sessions", "workspace_ref_id"):
        op.drop_column("agent_sessions", "workspace_ref_id")

    op.add_column("plugins", sa.Column("source", sa.JSON(), nullable=True))
    op.add_column("skills", sa.Column("source", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("skills", "source")
    op.drop_column("plugins", "source")
    op.add_column(
        "agent_sessions",
        sa.Column("workspace_ref_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "agent_sessions",
        sa.Column(
            "workspace_scope",
            sa.VARCHAR(length=50),
            server_default=sa.text("'session'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_agent_sessions_workspace_scope"),
        "agent_sessions",
        ["workspace_scope"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_sessions_workspace_ref_id"),
        "agent_sessions",
        ["workspace_ref_id"],
        unique=False,
    )
    op.add_column(
        "agent_scheduled_tasks",
        sa.Column(
            "workspace_scope",
            sa.VARCHAR(length=50),
            server_default=sa.text("'session'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "agent_scheduled_tasks",
        sa.Column("project_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("agent_scheduled_tasks_project_id_fkey"),
        "agent_scheduled_tasks",
        "projects",
        ["project_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_index(
        op.f("ix_agent_scheduled_tasks_workspace_scope"),
        "agent_scheduled_tasks",
        ["workspace_scope"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_scheduled_tasks_project_id"),
        "agent_scheduled_tasks",
        ["project_id"],
        unique=False,
    )
    op.add_column(
        "agent_runs",
        sa.Column("workspace_ref_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "agent_runs",
        sa.Column(
            "workspace_scope",
            sa.VARCHAR(length=50),
            server_default=sa.text("'session'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_agent_runs_workspace_scope"),
        "agent_runs",
        ["workspace_scope"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_runs_workspace_ref_id"),
        "agent_runs",
        ["workspace_ref_id"],
        unique=False,
    )
    # ### end Alembic commands ###
