"""add admin_disabled to skills

Revision ID: 536bf6b4ee0c
Revises: 20260430_runtime_env_policy
Create Date: 2026-05-06 06:40:42.601580

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "536bf6b4ee0c"
down_revision: Union[str, Sequence[str], None] = "20260430_runtime_env_policy"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "skills",
        sa.Column(
            "admin_disabled",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("skills", "admin_disabled")
    # ### end Alembic commands ###
