"""empty message

Revision ID: 604f9cc61bd7
Revises: 399bf32a2a75
Create Date: 2026-01-29 19:37:56.386820

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "604f9cc61bd7"
down_revision: Union[str, Sequence[str], None] = "399bf32a2a75"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agent_runs",
        sa.Column(
            "permission_mode",
            sa.String(length=50),
            nullable=False,
            server_default="default",
        ),
    )
    op.create_index(
        op.f("ix_agent_runs_permission_mode"),
        "agent_runs",
        ["permission_mode"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_agent_runs_permission_mode"), table_name="agent_runs")
    op.drop_column("agent_runs", "permission_mode")
    # ### end Alembic commands ###
