name: CI Prettier

on:
  pull_request:
    paths-ignore:
      - backend/assets/**
  push:
    branches:
      - main
    paths-ignore:
      - backend/assets/**
  workflow_dispatch:

permissions:
  contents: read

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install pre-commit
        run: python -m pip install pre-commit

      - name: Run Prettier Check
        run: pre-commit run prettier --all-files --show-diff-on-failure
